[package]
name = "open_fortress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = [
    "dwarf_plugin/debug",
    "fps_plugin/debug",
    "bevy-inspector-egui",
    "data/debug"
]

[dependencies]
bevy = "0.9.1"
bevy-inspector-egui = { version = "0.14.0", optional = true }

data = { path = "data" }
dwarf_plugin = { path = "dwarf_plugin" }
fps_plugin = { path = "fps_plugin" }

[workspace]
members = [
    "dwarf_plugin",
    "fps_plugin",
    "data"
]