[package]
name = "open_fortress"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
fps = []
debug = []
inspector = [
    "bevy-inspector-egui",
]

[dependencies]
bevy = "0.9.1"
bevy-inspector-egui = { version = "0.14.0", optional = true }
priority-queue = "1.3.0"
