[package]
name = "dwarf"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
animation = { path = "../animation" }
assets = { path = "../assets" }
common = { path = "../common" }
work = { path = "../work" }