[package]
name = "main_game"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
camera = { path = "../camera"}
common = { path = "../common"}
dwarf = { path = "../dwarf"}
map_generation = { path = "../map_generation" }